version: 0.2

phases:
  install:
    run-as: root
    on-failure: ABORT
    runtime-versions:
      docker: 18
      python: 3.8
    commands:
      - echo "some tests ect..."

artifacts:
  files:
    - "**/*"
  name: build-$(date +%Y-%m-%d)
