version: 0.2

phases:
  install:
    run-as: root
    runtime-versions:
      docker: 18
      python: 3.8
    commands:
      - echo "test"
artifacts:
  files:
    - '**/*'
    name: build-$(date +%Y-%m-%d)
