---
- hosts: localhost
  tasks:
    - name: Ensure nginx is at the latest version
      apt: name=nginx state=latest
    - name: start nginx
      service:
          name: nginx
          state: started

    - name: copy the nginx config file and restart nginx
      copy:
        src: /root/assignment/files/default
        dest: /etc/nginx/sites-available/default
      become: yes
  
  

    - name: enable configuration
      file: >
        dest=/etc/nginx/sites-enabled/default
        src=/etc/nginx/sites-available/default
        state=link
      become: yes


    - name: copy the content of the web site
      copy:
        src: /root/assignment/files/helloworld.html
        dest: /var/www/html/helloworld/


    - name: restart nginx
      service:
        name: nginx
        state: restarted
      become: yes
