---
- hosts: localhost
  tasks:
    - name: Ensure nginx is at the latest version
      apt: name=nginx state=latest
    - name: start nginx
      service:
          name: nginx
          state: started

    - name: copy the nginx config file 
      copy:
        src: /root/assignment/files/default
        dest: /etc/nginx/sites-available/default

    - name: enable configuration
      file: >
        dest=/etc/nginx/sites-enabled/default
        src=/etc/nginx/sites-available/default
        state=link


    - name: copy the content of the web site
      copy:
        src: /root/assignment/files/helloworld.html
        dest: /var/www/html/helloworld/


    - name: restart nginx
      service:
        name: nginx
        state: restarted


    - name: copy unit file to correct directory
      copy:
        src: /root/assignment/files/webservers.service 
        dest: /etc/systemd/system/webservers.service
        mode: +x

    - name: daemon reload and start webservers
      systemd:
        name: webservers.service
        daemon_reload: yes
        enabled: yes
        state: started
